#### This is the child pipeline that is integrated in the main pipeline .gitlab-ci.yml. This will run as a separate pipeline and
#### in its own separate container, separate from the deploy pipeline container. This runs a native pytest image and pytest is 
#### added with pip install. 
#### There is no nded to COPY or mount the repo as gitlab does that automatically for every job container
#### by default. The deploy pipeline required a specific COPY of a subdirectory of the root repo directory and thus requires a 
#### COPY command in the docker image that it uses (build push and deploy). This pytest pipeline will run the pytest test file in 
#### the tests directory off the root of the repo by using the default mount that gitlab does for all containers. 
#### pytest -v -s --capture=no tests/test_ai_hook_v7.py | tee pytest-report.log  <<< the logs will be piped to a log file and 
#### these will be in the artifact logs for the child pipeline which can be downloaded in the Gitabl web console.

stages:
  - pytest

pytest_job:
  stage: pytest
  image: python:3.12
  tags:
    - docker1   #### added the tag docker in the /etc/gitlab-runner/config.toml file for the docker executor. Make sure to use docker1 here. this is for the docker executor of instance type (not project or group type)
  
  script:
    - pip install PyYAML==6.0.1 ## the PyYAML 6.0 dependency has trouble with installing on 3.12, so hardcode override this one.
    - pip install -r aws_boto3_modular_multi_processing/requirements.txt ## the pytest requires all python depenedencies that the actual deployment scripts rdquire. This docker container for the pytest suite is bare bones and we need to add them to it.
    - pip install pytest
    - pytest -v -s --capture=no tests/test_ai_hook_v7.py | tee pytest-report.log
  
  artifacts:
    when: always
    paths:
      - pytest-report.log
  only:
    - main
    - merge_requests
#### This will run on both merge_requests and on push requests.

#### note that this uses the docker executor gitlab runner, so must enable access to this executor in the runner settings under
#### CI/CD in the gitlab web console for this PROJECT.
#### Make sure the docker executor is also allowed to run on this protected branch in the Admin settings.
