FROM python:3.11.9
WORKDIR /aws_EC2
ENV PYTHONUNBUFFERED=1

COPY ./aws_boto3_modular_no_multi_threading /aws_EC2
RUN pip install --no-cache-dir -r requirements.txt

# original for AWS2
#CMD ["python", "master_sequential_for_docker_run_in_linux_order_with_variable_delays_USE.py"]

# use with AWS3 setup
#CMD ["python", "-u", "master_sequential_for_docker_run_in_linux_order_with_variable_delays_USE_AWS3_ONLY_debug.py"]

# the new wrapper script to run tuples in parallel to optimize the thread execution of the python script files
# Only the files that can be run together without dependencies between them should be run in parallel. Otherwise
# the default is to run the files sequentially if not specified in the parallel_ranges array.
#CMD ["python", "-u", "master_sequential_for_docker_run_in_linux_order_with_variable_delays_USE_AWS3_ONLY_debug_PARALLEL_THREAD.py"]

# This is for python modules case.  This is without parallelization (multi-threading or multi-processing) of the modules for now. Will get to that later.
CMD ["python", "-u", "master_script.py"]
