FROM python:3.11.9
WORKDIR /aws_EC2
ENV PYTHONUNBUFFERED=1

# Confirm default shell
RUN echo "Default shell: $(readlink /bin/sh)"

# Install Bash to ensure proper stream redirection
RUN apt-get update && apt-get install -y bash


#COPY ./aws_boto3_modular_multi_processing /aws_EC2

COPY . /aws_EC2
# this is to accomodate the pytest test stage. The pytest test cases are in root and so if container runs them, the entire
# root repo has to be copied over to the container.





#RUN pip install --no-cache-dir -r requirements.txt

# fix the path to requirements.txt now that entire root directory of repo is copied over into container for test stage pytest 
# CI integration
RUN pip install --no-cache-dir -r aws_boto3_modular_multi_processing/requirements.txt





# Install pytest for the test stage that will run the pytest test cases
RUN pip install pytest





# original for AWS2
#CMD ["python", "master_sequential_for_docker_run_in_linux_order_with_variable_delays_USE.py"]

# use with AWS3 setup
#CMD ["python", "-u", "master_sequential_for_docker_run_in_linux_order_with_variable_delays_USE_AWS3_ONLY_debug.py"]

# the new wrapper script to run tuples in parallel to optimize the thread execution of the python script files
# Only the files that can be run together without dependencies between them should be run in parallel. Otherwise
# the default is to run the files sequentially if not specified in the parallel_ranges array.
#CMD ["python", "-u", "master_sequential_for_docker_run_in_linux_order_with_variable_delays_USE_AWS3_ONLY_debug_PARALLEL_THREAD.py"]


########### use for multi-processing forked version
#CMD ["python", "master_script.py"]

############ use for multi-processing spawn version
CMD ["python", "master_script_spawn.py"]




