FROM python:3.11.9
WORKDIR /aws_EC2
ENV PYTHONUNBUFFERED=1


COPY ./aws_boto3_modular_multi_processing /aws_EC2
RUN pip install --no-cache-dir -r requirements.txt

# original for AWS2
#CMD ["python", "master_sequential_for_docker_run_in_linux_order_with_variable_delays_USE.py"]

# use with AWS3 setup
#CMD ["python", "-u", "master_sequential_for_docker_run_in_linux_order_with_variable_delays_USE_AWS3_ONLY_debug.py"]

# the new wrapper script to run tuples in parallel to optimize the thread execution of the python script files
# Only the files that can be run together without dependencies between them should be run in parallel. Otherwise
# the default is to run the files sequentially if not specified in the parallel_ranges array.
#CMD ["python", "-u", "master_sequential_for_docker_run_in_linux_order_with_variable_delays_USE_AWS3_ONLY_debug_PARALLEL_THREAD.py"]


# use for multi-processing

## FOR manual testing comment out this line
#CMD ["python", "master_script.py"]
